name: vclibs
description: Let your flutter windows apps include vclibs.
version: 0.0.1
homepage: https://github.com/leanflutter/vclibs

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: VclibsPlugin
